name: "Label conflicting PRs"
on:
  push:
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write

jobs:
  main:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Label conflicting PRs
        uses: eps1lon/actions-label-merge-conflict@v3.0.2
        with:
          dirtyLabel: "unresolved-merge-conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "Please take a moment and address the merge conflicts of your pull request. Thanks!"
          continueOnMissingPermissions: true
