name: Run update-since-todo.py

on:
  schedule:
    - cron: "0 16 * * THU"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  since_updater:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'jenkinsci' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Run update-since-todo.py
        run: |
          body=$(./update-since-todo.py)

          {
            echo 'PROGRESS<<EOF'
            echo "${body}"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        id: run_script
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Fill in since annotations
          title: Fill in since annotations
          body: ${{ steps.run_script.outputs.PROGRESS }}
          base: master
          labels: skip-changelog
          branch: actions/update-since-todo
          delete-branch: true
